from enum import Enum

class DeliveryMethod(Enum):
    MAILING = "MAILING"
    ONLINE = "ONLINE"
    COURIER = "COURIER"
    VRCARGO = "VRCARGO"
    BUS = "BUS"
    FREIGHT = "FREIGHT"
    RETRIEVABLE = "RETRIEVABLE"
    OTHER = "OTHER"


class InvoiceSendingMethod(Enum):
    EMAIL = "EMAIL"
    MAIL = "MAIL"
    ELECTRONIC_INVOICE = "ELECTRONIC_INVOICE"
    EDIFACT = "EDIFACT"
    PAPER_INVOICE = "PAPER_INVOICE"
    NO_SENDING = "NO_SENDING"
    
    
class Language(Enum):
    ENGLISH = "ENGLISH"
    FINNISH = "FINNISH"
    SWEDISH = "SWEDISH"
    ESTONIAN = "ESTONIAN"
    NORWEGIAN = "NORWEGIAN"
    DANISH = "DANISH"
    
class DocumentInvoiceType(Enum):
    SALES_INVOICE = "SALES_INVOICE"
    SALES_ORDER = "SALES_ORDER"
    PURCHASE_INVOICE = "PURCHASE_INVOICE"
    PURCHASE_ORDER = "PURCHASE_ORDER"
    TRAVEL_INVOICE = "TRAVEL_INVOICE"
    BILL_OF_CHARGES = "BILL_OF_CHARGES"
    PERIODIC_TAX_RETURN = "PERIODIC_TAX_RETURN"
    
class PaymentType(Enum):
    RF = "RF"
    FI = "FI"
    OCR = "OCR"
    KID = "KID"
    GIK01 = "GIK01"
    GIK04 = "GIK04"
    GIK15 = "GIK15"
    FIK71 = "FIK71"
    FIK73 = "FIK73"
    FIK75 = "FIK75"
    
class cashDiscountsType(Enum):
    FROM_INV_DATE = "FROM_INV_DATE"
    FROM_END_OF_MONTH = "FROM_END_OF_MONTH"
    

class ReferenceType(Enum):
    INVOICE = "INVOICE"
    LEDGERRECEIPT = "LEDGERRECEIPT"
    BANKSTATEMENTEVENT = "BANKSTATEMENTEVENT"
    SALES_PRODUCT_REGISTER = "SALES_PRODUCT_REGISTER"
    PURCHASE_PRODUCT_REGISTER = "PURCHASE_PRODUCT_REGISTER"
    CUSTOMER_BUSINESS_PARTNER_REGISTER = "CUSTOMER_BUSINESS_PARTNER_REGISTER"
    SUPPLIER_BUSINESS_PARTNER_REGISTER = "SUPPLIER_BUSINESS_PARTNER_REGISTER"
    PERSON_BUSINESS_PARTNER_REGISTER = "PERSON_BUSINESS_PARTNER_REGISTER"
    EMPLOYEE_INFO = "EMPLOYEE_INFO"
    ENVIRONMENT = "ENVIRONMENT"
    FINANCIAL_STATEMENT = "FINANCIAL_STATEMENT"
    NETS_COLLECTION = "NETS_COLLECTION"
    REFERENCE_PAYMENT = "REFERENCE_PAYMENT"
    INVOICEDRAFT_ITEM = "INVOICEDRAFT_ITEM"
    COST_RECEIPT = "COST_RECEIPT"


